export const DEBUG = {
  BOT_CIRCLES: true,
  CHASE: true,
  OPEN_WAYPOINTS: false,
  COLLISON: false,
  IS_CLEAR: false,
  IT_CHOICE: false,
  LOST: false,
  MAKE_IT: false,
  NOT_IT_CHOICE: true,
  PATHING: true,
  POSITION: false,
  SPEED: false,
  STEP_TIME: true,
  STEP_TIME_LIMIT: 35,
  WANDER: false,
  WAYPOINT_CIRCLES: true,
  WAYPOINT_LABELS: false,
  GRID_CIRCLES: false
}
